### ISSUE TITLE
Improve Run As > ... menu to include best practice and most common commands

### ISSUE THREAD

**Issue by gamerson** [gamerson/poshi-ide#18]
`ant -f build-test-tomcat.xml run-selenium-tomcat -Dtest.class=`

**Comment by brianchiu** [comment]
@gamerson 

Here are the two commands that we should be running
1. Will start up Liferay Portal for you

```
ant -f build-test-tomcat.xml run-selenium-tomcat -Dtest.class=${command}
```
1. Assumes you already have Liferay Portal started up

```
ant -f build-test.xml run-selenium-test -Dtest.class=${command}
```

Where ${command} comes in the form of ${testCaseFile}#${testCaseCommand} like PGBlogs#AddBlogsEntry.

So, there's another thing that Hashi wrote to check syntax. It's similar to what "build-selenium" does (that you'll see under the Poshi > menulist in the context menu). However, if eclipse is able to do this on its own (like highlighting when things would break like you talked about), we wouldn't need this command.

```
ant -f build-test.xml run-poshi-validation
```
