### ISSUE TITLE
Add code assist for locator1/locator2 (.path files not in Path folder)

### ISSUE THREAD

**Issue by jtydhr88** [gamerson/poshi-ide#26]

**Comment by AndyWu2015** [comment]
Attentions : execute time is slow cause many path files and tags  , first time run ALt+/ about 3s , and later 2.5s

**Comment by gamerson** [comment]
Hey Andy,

Can you add a new issue about this slowness?  We should be able to add a
cache of path files to speed this up.

On Thu, Sep 17, 2015 at 2:30 AM, Andy Wu notifications@github.com wrote:

> Attentions : execute time is slow cause many path files and tags , first
> time run ALt+/ about 3s , and later 2.5s
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gamerson/poshi-ide/issues/26#issuecomment-140991888.

## 

Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
We don't have to fix the speed issue for 1.1 but we should address it in
the future at some point.

On Thu, Sep 17, 2015 at 10:14 AM, Greg Amerson gregory.amerson@liferay.com
wrote:

> Hey Andy,
> 
> Can you add a new issue about this slowness?  We should be able to add a
> cache of path files to speed this up.
> 
> On Thu, Sep 17, 2015 at 2:30 AM, Andy Wu notifications@github.com wrote:
> 
> > Attentions : execute time is slow cause many path files and tags , first
> > time run ALt+/ about 3s , and later 2.5s
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gamerson/poshi-ide/issues/26#issuecomment-140991888.
> 
> ## 
> 
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com

## 

Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
got it
